apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-gcp-mysql
  namespace: mysql-backups
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  schedule: "0 5 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: backup-gcp-mysql
    spec:
      activeDeadlineSeconds: 3600  # Kill job after 1 hour
      backoffLimit: 3
      completions: 1
      parallelism: 1
      ttlSecondsAfterFinished: 3600  # Retain job for 1 hour after finish
      template:
        metadata:
          labels:
            app: backup-gcp-mysql
        spec:
          containers:
          - name: backup-job
            image: ghcr.io/natrontech/gcp-mysql-backup:latest
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 32Mi
            env:
              - name: MYSQL_HOST
                value: "127.0.0.1"
              - name: MYSQL_PORT
                value: "3306"
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: backup-gcp-mysql
                    key: MYSQL_USER
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: backup-gcp-mysql
                    key: MYSQL_PASSWORD
              - name: MYSQL_DATABASES
                value: "db1, db2, db3" # Add more databases separated by comma
              - name: GCP_BUCKET
                value: "backups"
              - name: GCP_BUCKET_DIR
                value: "mysql"
              - name: PROXY_QUIT_URL
                value: "http://localhost:9091/quitquitquit"
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2
            imagePullPolicy: Always
            args:
              - '--exit-zero-on-sigterm'
              - '--quitquitquit'
              - '--port=3306'
              - project-id:region:instance-name # Replace with your project-id, region and instance name
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 256Mi
            securityContext:
              runAsNonRoot: true
          restartPolicy: OnFailure
          serviceAccountName: backup-gcp-mysql
          serviceAccount: backup-gcp-mysql
          automountServiceAccountToken: true
          securityContext:
            runAsUser: 1001
            runAsGroup: 3000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
